<?php $form->prepare(); ?>
<?php $form->setAttribute("action", $this->url("contact-add", array("action" => "add"))); ?>

<section class="col col-lg-8">

    <?php echo $this->form()->openTag($form); ?>
    <?php $contacts = $form->get("contacts"); ?>
    <?php #\Zend\Debug\Debug::dump($contacts) ?>

    <fieldset>
        <legend>Add</legend>
        <ul class="ul-add">
            <li><?php echo $this->formRow($contacts->get("firstName")); ?></li>
            <li><?php echo $this->formRow($contacts->get("lastName")); ?></li>
            <li><?php echo $this->formRow($contacts->get("address")); ?></li>
            <li><?php echo $this->formRow($contacts->get("contactType")); ?></li>                
            <li>
                <div id="email-wrapper">
                    <?php echo $this->formCollection($contacts->get("emails")); ?>
                </div>                
            </li>                
            <li><a id="add-email" class="btn btn-primary">Add a new Email</a></li>
            <li>
                <div id="phone-wrapper">
                    <?php echo $this->formCollection($contacts->get("phones")); ?>
                </div>                
            </li>                
            <li><a id="add-phone" class="btn btn-primary">Add a new Phone</a></li>                                        
            <li><?php echo $this->formRow($contacts->get("active")); ?></li>                                        
            <li><?php echo $this->formSubmit($form->get("submit")); ?></li>
        </ul>
        <?php echo $this->formHidden($form->get("csrf")); ?>
    </fieldset>
    <?php echo $this->form()->closeTag(); ?>

</section>

<link href="<?php echo "/css/abook-style.css"; ?>" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="/js/abook-javascript.js"></script>
