<?php $form->prepare(); ?>
<?php $form->setAttribute("action", $this->url("contact-add", array("action" => "add"))); ?>

<section class="col col-lg-8">
    
    <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            <legend>Add</legend>
            <ul class="ul-add">
                <li><?php echo $this->formRow($form->get("first_name")); ?></li>
                <li><?php echo $this->formRow($form->get("last_name")); ?></li>
                <li><?php echo $this->formRow($form->get("address")); ?></li>
                <li><?php echo $this->formSubmit($form->get("submit")); ?></li>
            </ul>
        </fieldset>
    <?php echo $this->form()->closeTag(); ?>
    
</section>

<style type="text/css">
    .ul-add li { list-style: none }
</style>