<?php if(!is_null($message)) : ?>
    <h3><?php echo $message; ?></h3>
<?php else : ?>
    
<?php $form->prepare(); ?>
<?php $contacts = $form->get("contacts"); ?>

<?php $form->setAttribute("action", $this->url("contact-edit", array("action" => "edit", "id" => $id))); ?>

<section class="col col-lg-8">    
    <?php echo $this->form()->openTag($form); ?>
    <?php #\Zend\Debug\Debug::dump($contacts); ?>
    <fieldset>
        <legend>Edit</legend>
        <ul class="ul-add">
            <li><?php echo $this->formRow($contacts->get("firstName")); ?></li>
            <li><?php echo $this->formRow($contacts->get("lastName")); ?></li>
            <li><?php echo $this->formRow($contacts->get("address")); ?></li>
            <li><?php echo $this->formRow($contacts->get("contactType")); ?></li>
            <li>
                <div id="email-wrapper">
                    <?php echo $this->formCollection($contacts->get("emails")); ?>
                </div>                
            </li>                
            <li><a id="add-email" class="btn btn-primary">Add a new Email</a></li>              
            <li>
                <div id="phone-wrapper">
                    <?php echo $this->formCollection($contacts->get("phones")); ?>
                </div>                
            </li>                
            <li><a id="add-phone" class="btn btn-primary">Add a new Phone</a></li>
            <li><?php echo $this->formRow($contacts->get("active")); ?></li>
            <li><?php echo $this->formSubmit($form->get("submit")); ?></li>
        </ul>
        <?php echo $this->formHidden($contacts->get("id")); ?>
        <?php echo $this->formHidden($form->get("csrf")); ?>
    </fieldset>
    <?php echo $this->form()->closeTag(); ?>

</section>

<link href="/css/abook-style.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="/js/abook-javascript.js"></script>

<?php endif; ?>