<?php $form->prepare(); ?>
<?php $contacts = $form->get("contacts"); ?>

<?php $form->setAttribute("action", $this->url("contact-edit", array("action" => "edit", "id" => $id))); ?>

<section class="col col-lg-8">    
    <?php echo $this->form()->openTag($form); ?>
    <?php #\Zend\Debug\Debug::dump($contacts); ?>
        <fieldset>
            <legend>Edit</legend>
            <ul class="ul-add">
                <li><?php echo $this->formRow($contacts->get("firstName")); ?></li>
                <li><?php echo $this->formRow($contacts->get("lastName")); ?></li>
                <li><?php echo $this->formRow($contacts->get("address")); ?></li>
                <li><?php echo $this->formRow($contacts->get("contactType")); ?></li>
                <li><?php echo $this->formCollection($contacts->get("emails")); ?></li>                
                <li><?php echo $this->formCollection($contacts->get("phones")); ?></li>                 
                <li><?php echo $this->formRow($contacts->get("active")); ?></li>
                <li><?php echo $this->formSubmit($form->get("submit")); ?></li>
            </ul>
            <?php echo $this->formHidden($contacts->get("id")); ?>
            <?php echo $this->formHidden($form->get("csrf")); ?>
        </fieldset>
    <?php echo $this->form()->closeTag(); ?>
    
</section>

<style type="text/css">
    .ul-add li { list-style: none; margin-bottom: 10px; }    
    input[type="text"] { width: 440px; }
</style>