<?php $form->prepare(); ?>
<?php $contacts = $form->get("contacts"); ?>

<?php $form->setAttribute("action", $this->url("contact-edit", array("action" => "edit", "id" => $id))); ?>

<section class="col col-lg-8">    
    <?php echo $this->form()->openTag($form); ?>
    <?php #\Zend\Debug\Debug::dump($contacts); ?>
    <fieldset>
        <legend>Edit</legend>
        <ul class="ul-add">
            <li><?php echo $this->formRow($contacts->get("firstName")); ?></li>
            <li><?php echo $this->formRow($contacts->get("lastName")); ?></li>
            <li><?php echo $this->formRow($contacts->get("address")); ?></li>
            <li><?php echo $this->formRow($contacts->get("contactType")); ?></li>
            <li>
                <div id="email-wrapper">
                    <?php echo $this->formCollection($contacts->get("emails")); ?>
                </div>                
            </li>                
            <li><a id="add-email" class="btn btn-primary">Add a new Email</a></li>              
            <li>
                <div id="phone-wrapper">
                    <?php echo $this->formCollection($contacts->get("phones")); ?>
                </div>                
            </li>                
            <li><a id="add-phone" class="btn btn-primary">Add a new Phone</a></li>
            <li><?php echo $this->formRow($contacts->get("active")); ?></li>
            <li><?php echo $this->formSubmit($form->get("submit")); ?></li>
        </ul>
        <?php echo $this->formHidden($contacts->get("id")); ?>
        <?php echo $this->formHidden($form->get("csrf")); ?>
    </fieldset>
    <?php echo $this->form()->closeTag(); ?>

</section>

<style type="text/css">
    .ul-add li { list-style: none; margin-bottom: 10px; }    
    input[type="text"] { width: 690px; }
</style>

<script type="text/javascript">

    $(function() {

        $(document).on("click", "#add-email, #add-phone", function() {
            var btn = $(this).attr("id");
            insert(btn);
        });

        function insert(btn) {

            switch (btn) {
                case 'add-email' :
                    var wrapper = "#email-wrapper";
                    break;
                case 'add-phone' :
                    var wrapper = "#phone-wrapper";
                    break;
            }

            var currentCount = $(wrapper + " > fieldset > .form-control").length;
            var template = $(wrapper + " > fieldset > span").data("template");
            template = template.replace(/__index__/g, currentCount);
            $(wrapper + " > fieldset").append(template);
            return false;
        }

        $(document).on("click", "#rem", function() {

            $(this).prev().prev().attr("data-delete", "on");            
            $(this).prev().attr("data-delete", "on");            
            $(this).attr("data-delete", "on");            
            
            $("*[data-delete='on']").remove();
        });

    });

</script>