<table border="1">
    <thead>
        <tr>
            <th>#</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($contacts as $row) : ?>
        <tr>
            <?php foreach ($row as $col) : ?>
            <td><?php echo $col; ?></td>
            <?php endforeach; ?>        
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>