<div class="row">
    <fieldset>
        <legend>List contacts</legend>
        
        <?php if (sizeof($contacts) == 0) : ?>
            <span>No found results.</span>
        <?php else : ?>

            <table class="table table-striped table-bordered table-condensed table-hover">

                <thead>
                    <tr>
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Address</th>
                        <th>Type</th>
                        <th>Active</th>                        
                    </tr>
                </thead>

                <tbody>

                    <?php foreach ($contacts as $contact) : ?>
                    
                    <tr>
                        <td><a href="<?php echo $this->url('contact-edit', array("id"=>$contact->id)) ?>"><?php echo $contact->id; ?></a></td>
                        <td><?php echo $contact->firstName; ?></td>
                        <td><?php echo $contact->lastName; ?></td>
                        <td><?php echo $contact->address; ?></td>
                        <td><?php echo $contact->contactType; ?></td>
                        <td><?php echo ($contact->active) ? "Yes" : "No"; ?></td>                        
                    </tr>
                    
                    <?php endforeach; ?>                    

                </tbody>

            </table>

        <?php endif; ?>
    </fieldset>
</div>

<style type="text/css">
    
</style>