<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Address Book ' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <section class="container">
            <div class="content row">
                <section class="main col col-lg-8">

                    <div class="content row">
                        <div class="col-lg-12">
                            <header class="clearfix ">

                                <div class="navbar navbar-fixed-top navbar-default">                                
                                    <ul class="nav navbar-nav">
                                        <li>
                                            <a href="<?php echo $this->url('home') ?>">
                                                <img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Address Book"/>
                                                &nbsp;<?php echo $this->translate('Address Book') ?></a>
                                        </li>
                                        <li>
                                            <a href="<?php echo $this->url('contact-add') ?>">
                                                <div class="glyphicon glyphicon-plus-sign"></div>
                                                &nbsp;<?php echo $this->translate('Add Contact') ?>
                                            </a></li>
                                        <li>
                                            <a href="<?php echo $this->url('contact-list') ?>">
                                                <div class="glyphicon glyphicon-list"></div>
                                                &nbsp;<?php echo $this->translate('List Contact') ?>
                                            </a>
                                        </li>                                        
                                    </ul><!--nav-->
                                </div><!--navbar-->

                            </header><!--header-->
                        </div><!--column-->                        
                    </div><!--content-->
                    <div class="content">
                        <div class="content"><?php echo $this->content; ?></div>
                    </div>
                </section><!--main-->
                <section class="sidebar col col-lg-4">

                </section><!--sidebar-->
            </div><!--content row-->
        </section><!--container--> 
    </body>
</html>
