<style type="text/css">    
    .ul-add li { padding: 5px  }
</style>
<?php 
    $form->prepare(); 
    $form->setAttribute('action', $this->url('contact-add', array('action' => 'add')));
?>
<div class="row">
    <?php echo $this->form()->openTag($form); ?>
    <fieldset>
        <legend>Add contact</legend>
        
        <ul class="ul-add">
            <li>
                <?php echo $this->formRow($form->get("first_name")); ?>
            </li>
            <li>
                <?php echo $this->formRow($form->get("last_name")); ?>
            </li>
            <li>
                <?php echo $this->formRow($form->get("address")); ?>
            </li>
            <li>                
                <?php echo $this->formSubmit($form->get("submit")); ?>
            </li>
        </ul>               
        
    </fieldset>
    <?php echo $this->form()->closeTag(); ?>
</div>