<div class="row">
    <fieldset>
        <legend>List contacts</legend>
        <?php if (sizeof($contacts) == 0) : ?>
            <span>No found results.</span>
        <?php else : ?>

            <table class="table table-striped table-bordered table-condensed table-hover">

                <thead>
                    <tr>
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Address</th>
                    </tr>
                </thead>

                <tbody>

                    <?php foreach ($contacts as $contact) : ?>
                        <tr>
                            <td><?php echo $contact->idc; ?></td>
                            <td><?php echo $contact->fname; ?></td>
                            <td><?php echo $contact->lname; ?></td>
                            <td><?php echo $contact->address; ?></td>
                        </tr>
                    <?php endforeach; ?>                    

                </tbody>

            </table>

        <?php endif; ?>
    </fieldset>
</div>